import React from "react";
import PackageCard from "../Prices/PackageCard";
import "./Projects.css";
import WebCard from "./WebCard";

function VideoProjects() {
  return (
    <div className="video-projects services">
      <h2>Video Editing</h2>
      <p>
        High-quality video editing services that help you tell your brand’s
        story and connect with your audience through engaging visuals and
        compelling storytelling.
      </p>
      <div className="cards-container flex">
        <WebCard
          image='../../../assets/thumb3.png'
          title="4K Amritsar Cinematic Hyper-laps video | Heritage Street | Golden Temple | Wagah Border"
          button='Watch on YouTube'
          link='https://www.youtube.com/watch?v=T_HZlsywFow'
        />
        {/* https://www.youtube.com/watch?v=SVZyRJddlcI */}
        <WebCard
          image='../../../assets/podcast1.png'
          title='Uncover Success&Bizz Secret from Rajesh Kumar, Founder of@Kalvium A Million-Dollar Company'
          desc="Discover the blueprint for entrepreneurial success and learn how to navigate the challenges of the business world. This conversation covers important topics such as startups, funding, entrepreneurship, investors, business growth, and more. Don't miss this opportunity to gain valuable knowledge from one of India's most successful entrepreneurs!"
          button='Watch on YouTube'
          link='https://www.youtube.com/watch?v=SVZyRJddlcI'
        />
        <WebCard
          image='../../../assets/thumb1.jpg'
          title='Title'
          desc="Some part of the script for this video was generated by ChatGPT. I tried to make a very short film around this 'Title', but something does feel off to me. Please feel free to leave your suggestions in the comment section for improvement! :)"
          button='Watch on YouTube'
          link='https://www.youtube.com/watch?v=ZHOy4iDXanQ'
        />
        <WebCard
          image='../../../assets/thumb2.jpg'
          title="The Fate of Rubik's Cube | Stop-motion"
          button='Watch on YouTube'
          link='https://www.youtube.com/watch?v=NnRuj4iudak'
        />
      </div>

      <h2>Packages</h2>
        <div className='cards-container flex'>
          <PackageCard
            title = 'Basic'
            price = '$39'
            incl = {['Upto 7 mins', '2-3 Days Delivery', '1 Revision', 'YouTube, Reels, Shorts, TikTok', 'Transitions', 'Background Music']}
            notincl = {['Color Grading', 'Sound Design', 'Source File', 'Motion Graphics']}
          />
          <PackageCard
            title = 'Standard'
            price = '$99'
            incl = {['Upto 15 mins', '5-7 Days Delivery', '3 Revisions', 'YouTube, Reels, Shorts, TikTok', 'Transitions', 'Background Music', 'Color Grading', 'Sound Design']}
            notincl = {['Source File', 'Motion Graphics']}
          />
          <PackageCard
            title = 'Premium'
            price = '$149'
            incl = {['Upto 30 mins', 'On Requirements Delivery', '5 Revisions', 'YouTube, Reels, Shorts, TikTok', 'Transitions', 'Background Music', 'Color Grading', 'Sound Design', 'Source File', 'Motion Graphics']}
            notincl = {[]}
          />
        </div>
    </div>
  );
}

export default VideoProjects;
